server:
  port: 6541
spring:
  application:
    name: server-mq
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          dubbo:
            registry:
              address: nacos://127.0.0.1:8848
              use-as-metadata-center: false
            protocol:
              name: dubbo
              port: -1
            application:
              name: ${spring.application.name}
            cloud:
              subscribed-services: server-mq
            consumer:
              retries: 0
              timeout: 99999
            provider:
              retries: 0
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    use-as-metadata-center: false
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}
  cloud:
    subscribed-services: proprietor-service
  consumer:
    retries: 0
    timeout: 99999
  provider:
    retries: 0
    timeout: 99999