server:
  port: 9527
#  ssl:
#    key-store: classpath:6363490_api.sq.wy.zhsj.co.pfx
#    key-store-password: H1w5C1hj
#    key-store-type: PKCS12
#    enabled: true

spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:1111
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowCredentials: true
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 跳转URL
        - id: property
          uri: lb://property-web
          predicates:
            - Path=/*/*/property/**

        - id: proprietor
          uri: lb://proprietor-web
          predicates:
            - Path=/*/*/proprietor/**

        - id: payment
          uri: lb://payment-web
          predicates:
            - Path=/*/*/payment/**

        - id: lease
          uri: lb://lease-web
          predicates:
            - Path=/*/*/lease/**
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    use-as-metadata-center: false
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}
  cloud:
    subscribed-services: server-gateway
  consumer:
    retries: 0
    timeout: 99999
  provider:
    retries: 0
    timeout: 99999