spring:
  redis:
    port: 6379
    host: 222.178.212.29
    password: smart99--
    database: 0
#    sms-databases: 7
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://222.178.212.29:3306/project_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: helloworld123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

minio:
  end-point: http://222.178.212.29
  port: 9000
  access-key: minio
  secret-key: minimini

# 光大银行云缴费请求地址
cebbank:
  private_key: MIIEpgIBAAKCAQEA5Dgb6BtLIYdFncWiXICX3r4e/wU8qPK0wxrBgBp69V+yvavS6UvBnESvq0tMYVXa36vdxsqyKpqWYG8jaFN7z758w2y3c3nGhtSfzOlUX+b987WJ8P+7/FSWbswkKOXXkwmTxs8E42ZPsPvcUQzYimIE3GM+36qyyoLoIzu1zrh2jhF/1gTrB5D41F8BRIqpoP8EHvdEqryO9sepNluU30HGw3CgBA2ciEI7cT5qsZ7F9IOFMdiwbFSuk/ZlQA9LebgLSOBEacXqX8IcjIuCfSGFmiepfjbwZwsmrtB/7VVp2paw0/wbgrUcuc0BWrPItlEGTafAjqO4qFLXnxmV1wIDAQABAoIBAQDeaghYdnEMJgcksb2AJRrdS7BtnS73AEJGesbmD+iRRkiuLMyJ7PitUQtbBzFTExcSMS8cU+K7PpkbNnTtcZ8SYXS6CDPpaF6gfIuYajV+mWIZp2zd4H3WdqF9LZp3+TfU5tqMQKlk7QrxUyPuIXTPuKNAHcDivjssvdN6svCGmsvTeMhFNBE5Mw94I7IlVwwU+Z4rnkb38hQBwyVHHCY0Q98jVe0E0rPSh9fe/UiswunaQV8f9ZMTBeytB1aGJB9e1/HG0qc5/+5Uyq8+HglbANipzBPhS33QLrrvc5UrSG4sL6412IMTy6scI268qSLTQ8+R2HRJg4Fd+Ldu2LWBAoGBAP2RqnKaJEZRttq999EZc+KXm7fyLzoKhfkkh9mP/1w+bhmOfznm1WKEBJg/NkREmTtFy6SlDPQ8aHy01d5ltzgBroAm4oVqxmEDT84QbDkLOn1AK4CMz0z/P2GrFzSNFzjevb1NKx+rZSBYKPfAc62/SP3PDx1yQ52+85oLKr63AoGBAOZoOiVAMF0Weqo7O7Tp75SGpspCEiRE3xqON+1NEbRfufBOaAvlWOX+MqVCow7ftElF4Fyi/4Yv5xDK5uQ4fBRCNe9nx3vRKAyuVCpLz5tuaiHbUyNNUnJjHsw6fS2HIavtUpKeo0mInRU1Z52CtxGsKCCFTDm0cfQv4gdRQMHhAoGBAIELxgwG6FklMwMF1P4EjxaNg8FMrr5CJsaR0dVmVFZUq2G0RIlqMcSuXUxCN1Ls+nLQ5X/IQ9x0ddSpj4Jcj68gI/eyUmwF2Cn9Lns3nmw1i7G8m6cTgli0OkRxdyDWgS//I98YS88VQiUA2PClb/nHtNT+sLmSsliwmncWIc3nAoGBAJGqSUBtsWXYpVpkMl4xG8dhzabHWKLXa9llGlSLSesoLeyQFVWX/LkDGU/DrkTkBx3f8HWAk11pgYLrVEfqsf840NJ3YPWViOVjfVB0N1+D0dNvzsLdyocIxVrGi4cyDIaednq9kmwV04GqDsTU9BpXJdNRkpxUyUpgz1xi8TbhAoGBAOcaqlRky+WkGXTtDn2LTYeqcXIjVYk0z/Dd419qVmBVzyxJsndIkCKywuUX8kxX59cEdIJHEzN2yLBoWK3iTZ3p/XN+2Oj73AaRMhaR3OcD2NerqYnuWiGfir8u5lN5Ne+DQ3wTZGNawxGvQNbcsMjctkSy6L6voeKAeHOxVf1v
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Dgb6BtLIYdFncWiXICX3r4e/wU8qPK0wxrBgBp69V+yvavS6UvBnESvq0tMYVXa36vdxsqyKpqWYG8jaFN7z758w2y3c3nGhtSfzOlUX+b987WJ8P+7/FSWbswkKOXXkwmTxs8E42ZPsPvcUQzYimIE3GM+36qyyoLoIzu1zrh2jhF/1gTrB5D41F8BRIqpoP8EHvdEqryO9sepNluU30HGw3CgBA2ciEI7cT5qsZ7F9IOFMdiwbFSuk/ZlQA9LebgLSOBEacXqX8IcjIuCfSGFmiepfjbwZwsmrtB/7VVp2paw0/wbgrUcuc0BWrPItlEGTafAjqO4qFLXnxmV1wIDAQAB
  request_url: https://yaoyaotest.cebbank.com/LifePayment/Test/yaoyaoAppInterface.json
  site_code: zonghengshiji
  version: 1.0.0
  charset: UTF-8