server:
  port: 8001
  servlet:
    context-path: /

spring:
  application:
    name: sys-community
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jsy.community.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: NONE
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jsy:
  shiro:
    redis: false
  jwt:
    # 加密秘钥
    secret: HL-A61332F5-ABC6-4D39-94C9-680EA8FB19ED
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

loginExpireHour: 12

email:
  host: smtp.qq.com
  baseAccount: 459799974@qq.com
  authPass: nfezhwyeduksbjjh
  linkExpiretime: 24