server:
  port: 9001
  servlet:
    context-path: /
rabbitmq:
  ####连接地址
  host: 106.13.84.80
  ####端口号
  port: 5672
  username: root
  password: root
  ### 地址
  virtual-host: /
  listener:
    simple:
      retry:
        ####开启消费者（程序出现异常的情况下会）进行重试
        enabled: true
        ####最大重试次数
        max-attempts: 5
        ####重试间隔次数
        initial-interval: 3000
      ####开启手动ack
      acknowledge-mode: MANUAL
spring:
  application:
    name: sys-community
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jsy.community.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: NONE
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jsy:
  shiro:
    redis: false
  jwt:
    # 加密秘钥
    secret: HL-A61332F5-ABC6-4D39-94C9-680EA8FB19ED
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
  #行驶证识别相关信息
  drivinglicense:
    api: https://api08.aliyun.venuscn.com
    path: /ocr/vehicle-license
    method: POST
    appCode: 9b53bb7f5f5945fcb4c42ecd79f31642

loginExpireHour: 12

email:
  host: smtp.qq.com
  baseAccount: 459799974@qq.com
  authPass: nfezhwyeduksbjjh
  linkExpiretime: 24

alipay:
  appid: dPHlJ8MTKFM/fTLpyfSzuFWQ8DMH1pOlHzcwcge1NVo=
  app-private-key: wQpN2EWIG6okLapioKJVTpeNxQ2USN4oepg/CTFqWUU+rKPfJS6YP5vVvmanvTcsJ2Nbelc2dztIzoznD71ymkdpDqLLVwHUwt35fDn/t/7I8JgdZqtqvZgr0AWTJcK28O8DcjQh+mz5Ooa7qtgzunkt+4l+XnWS2wopiJ4iqqEBVhy9uF8hs/7hTul6r6/m19H68cVKLlfdurpL5T7+rP7iKPScyM/dTP9EsnlvQgpJi2dTmTFAT0CCXRSnkVDR/2wZpvp09NG/luyEjecCgowhIPqytKjGUZNHp5JiLeUgnM1yNdzx0iZ4BXf6f6VNyQE45RwHKUgGhIqr6LzKvemA/II3e1hSjF2dHQY4maply82CuvGzDDXDjDycI59UDPI5Ls787P681a/wfF8GnMdk/KgTUUTzdVnK/N7DVrcDD5oz5LWn0Wc91a+SyjhkEr5OO5929dqfIikkjOIJDcYW4+qJ6+dqs1SsB7gIN+m8OSMJmQ1q4g+rIdIpBpdHj/ucyR1Bv8pqAcXoDhrxBXOiqPAlq+NwFJf7V2qxVA54x57WHSQVlZW9pF4cVoQxl7Y+IL+d5kVPnOIAWz3P0go5KkFyJTEWcItdBV5YklTfm5MHiVc7C0VQWukwwZilvDKr/QKFXFzwojSopqfmYl3SlI0MZStQobE0itPxpN9ySUr3ltdq2YPcCTlldvHnxr8v5IESZa79ZeyBMwrSbYCLCSEmElhFT/WFtZbjFs0/aXvXIlASJnc+k3wE000q+2FF38CdKBSKOMUdVLJGvG3crYbZ9i2K5zn3juJ7F/31z9ZSgTzKURubUfBHl347AvxCUU4AEh6Yvj9toB01So9I29alPSyzGs1WKvq1z7EyfFAd8dpG8zzH79FppgxXrnf96q+h9EUl42cyL4l0pE0MiIsvcIqUxN3SpYA1AVav0OZh5OwEgC5luBkgi1JeqoYqXxm+NqFU6lNqc9BzKvFS9mimG7oSR/TYssOoSSU8DTFO8vlRzZhamPtWXaJ6VZ2hKQVvNgez8yBeSaK22M/4s0kTv+IEkzNCM0kawIeRv4JIch79Qv/zm7DD3OUaZ51pAHc8YHBEbbPy03eqnoS/rIAScHT/hCWLNjmYyFBzDG4YWqQPGSW30VBEmFJMLmOgKa57Y1oSP053zPnevmjMF2elr6Jmr4AQROVI0DebCrfh5Gd45Xy08kZd4TdBs8YF035Hty80abQgW9GuzgTvqznZE+Oihd5ehIe0drXAk0NtJHV5jaAGhH/PjHK7yEIYMmPSMATT1fIatCBe3rVDQqrfj9AtJ3r6H0ar++ZH5kXKlrfIgp+sb+RrKiBnAtjbL5q0bZCrrW/m1Zw8VLA9q4MhVKsmu53IroL4JdvLXf/6/X8l5DSlGJKPJkJFeNoEVX/fzXPy/WQPb7L5U2+snXUMrY1PAFk+oI4B9yDRAuZLuxzduOhANUYsUmk2a6JhaksKCBsOc+p3bBpG4KfCU9bkaEsYqrP9gBPFhGzvkKrOacK6g+1oRGyKziRA1ItOeFujpL8RF+Hgl6HKDZrXcPIbjdd7rlTOldbA1rCUvub9GcNVxfM2AOaT43WccR91W2hkhffJbGLndluBpbplx1tggbi2ganqtghsBTMEm8Bgvz11T6A1vKfzPXjpAI9aEc0Dc2mbieLI8UxmDefBec8QnFXPsCsYj8RZ2t25zm/eSFs4kNpVblCVeKIWTWTVb3r3a79Dynq1miWfkGTI/LIRNcBArG5QZ2ShYBJmet4mg19Z3DwXcvzN8Tc2e5tl1rL6a3vhen21m/snctR9evWVNOqsWBhS8OyMANjQ7NMskdatGrszEfho+5lq2OI/NUH/H7LAWwVR7O0pKXAL59jFirvyO4gObyZ6T4yFe/g0/mzus+iw8c1JcqKqTUbrQAoX8UsxRTvasZB7ZMh6Z9vVMfmFLI+DkWBJWpVUzU0w2wh9M1a3nepggNo6nlckDuuectMKuodTC2VIqfuFWuHmhXGAZe+wQanBVJd1aH+t2ji4h0KFUkVFvOk3dMDIZ7ffE+tfNDeCAlwBTVw2yjJRTqzijQ4cFG7sq03aqHk7CfoHAgp1VVZOgG0wba98x8hxph5J6px+GYMfV3/vGhXE2suGYEX/fKHhrvzXX+eMBjlKWRw7kzqHG10i
  sellerId: TCxxMPqEGO2KNNI4zLodzMRhKHgHAnODd63fxygWKDI=
  sellerEmail: EsHo3RWOoNEgvOdUymo8Li8uy55aQoBVKU+mekm/SZk=
  sellerPID: TCxxMPqEGO2KNNI4zLodzMRhKHgHAnODd63fxygWKDI=
  cert-path:
    app-public-cert: /yMUV9bwkX/qWgXuuo3Tn0BIDZuj5lOfjdp/XztdQ15R+VEYa74K3asVSOsI9WCXDo4MVqWj4RqvYMe3ThdYumnZAyjwI3d1azh6DYX7H88=
    alipay-public-cert: /yMUV9bwkX/qWgXuuo3Tn0BIDZuj5lOfjdp/XztdQ15qbBLdzQJkM7QsnxbgB2Dc/1mbQsqE49BNhdf6kmsHDnA4BI+fU4byotb6SDlsUZ8=
    root-cert: /yMUV9bwkX/qWgXuuo3Tn0BIDZuj5lOfjdp/XztdQ17UiK8ZLIVZbCNVejlM24NyTkKoI4y8q+5+FyPuq655yQ==