server:
  port: 6001
  servlet:
    context-path: /

spring:
  application:
    name: propeietor-web-api

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 26001
  application:
    name: ${spring.application.name}

jsy:
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: XW-EC7D505B-3435-4728-9B04-84513C2BF0EE
    # token有效时长，7天，单位秒
    expire: 604800
    header: token