spring:
  redis:
    port: 6379
    host: 222.178.212.29
    password: smart99--
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 32
        # 连接池中的最小空闲连接 默认 0
        min-idle: 8