spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    port: 6379
    host: 222.178.212.29
    password: smart99--
    database: 0
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200
  rabbitmq:
    ####连接地址
    host: 106.13.84.80
    ####端口号
    port: 5672
    username: smart
    password: smart123
    ### 地址
    virtual-host: /
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔次数
          initial-interval: 3000
        ####开启手动ack
        acknowledge-mode: MANUAL
  upload:
    type: oss
  oss:
    aliyun:
      enable: true
      end-point: ada
      access-key-id: 2gaga
      access-key-secret: sgsagsd
      bucket-name: test
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: XW-EC7D505B-3435-4728-9B04-84513C2BF0EE
    # token有效时长，7天，单位秒
    expire: 604800
    header: token