spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    port: 6379
    host: 222.178.212.29
    password: smart99--
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 32
        # 连接池中的最小空闲连接 默认 0
        min-idle: 8

jsy:
  upload:
    type: oss
  oss:
    aliyun:
      enable: true
      end-point: ada
      access-key-id: 2gaga
      access-key-secret: sgsagsd
      bucket-name: test
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: XW-EC7D505B-3435-4728-9B04-84513C2BF0EE
    # token有效时长，7天，单位秒
    expire: 604800
    header: token